### ISSUE TITLE
Correct URL of Royal Society PDF

### ISSUE THREAD

**Issue by travisfranck** [climateinteractive/enroads-guide#10]
Currently we have a link to the Royal Society PDF as:

``https://royalsociety.org/ /media/policy/projects/greenhouse-gas-removal/royal-society-greenhouse-gas-removal-report-2018.pdf``

It should be 

``https://royalsociety.org/-/media/policy/projects/greenhouse-gas-removal/royal-society-greenhouse-gas-removal-report-2018.pdf``

Please note the '-' that is before 'media'.  It might have to be escaped in the reST document.

**Comment by llie** [comment]
I don't see this link anywhere in the Guide anymore, but we should add a citation for the two times we mention this report on: 

https://docs.climateinteractive.org/projects/en-roads/en/latest/guide/afforestation.html
https://docs.climateinteractive.org/projects/en-roads/en/latest/guide/tech_removal.html
