### ISSUE TITLE
Add Google Analytics to the user guide

### ISSUE THREAD

**Issue by llie** [climateinteractive/enroads-guide#11]
From Travis: 

> Do we want to gAnalytics on the RTD user guide? I see we could add it there. Not sure if we need another token what other GA setup is required.
> 
> https://readthedocs.org/dashboard/enroads-guide/advanced/

Sounds good to me to add GA to readthedocs.

**Comment by travisfranck** [comment]
@yasmeenzahar @llie I added Google Analytics to RTD now.  This for both C-ROADS and En-ROADS.  In the gAnalytics interface, it is a "property" of the ClimateInteractive "account".  This means you'll click "Climate Interactive" and then see ReadTheDocs and our WP site.
