### ISSUE TITLE
Add more on where to learn about the different types of CDR

### ISSUE THREAD

**Issue by llie** [climateinteractive/enroads-guide#14]
We should add more to explain the different types of CDR we have. 

Here are some fact sheets from American U that we might link to for people:

Agroforestry (https://www.american.edu/sis/centers/carbon-removal/fact-sheet-agroforestry.cfm)
BECCS: Bioenergy with carbon capture & storage (https://american.us19.list-manage.com/track/click?u=aefcb76ff1d91744e5f20bb45&id=2436879674&e=b9acf0ae8b
Biochar (https://american.us19.list-manage.com/track/click?u=aefcb76ff1d91744e5f20bb45&id=8852ba1c39&e=b9acf0ae8b)
Direct air capture (https://american.us19.list-manage.com/track/click?u=aefcb76ff1d91744e5f20bb45&id=030283f56b&e=b9acf0ae8b)
Enhanced mineralization (https://american.us19.list-manage.com/track/click?u=aefcb76ff1d91744e5f20bb45&id=783099f4d7&e=b9acf0ae8b)
Forestation (https://american.us19.list-manage.com/track/click?u=aefcb76ff1d91744e5f20bb45&id=f7ac7b57d2&e=b9acf0ae8b)
Soil carbon sequestration (https://american.us19.list-manage.com/track/click?u=aefcb76ff1d91744e5f20bb45&id=48d9f7197d&e=b9acf0ae8b)

**Comment by yasmeenzahar** [comment]
@llie are these finalized and good to be added to User Guide or is any more discussion needed?
