### ISSUE TITLE
Small edits to user guide - En-ROADS structure and Kaya

### ISSUE THREAD

**Issue by jchikofsky** [climateinteractive/enroads-guide#22]
En-ROADS structure section:
Under "1", there's the sentence "CO2 emissions comprise 67.5% of greenhouse gas emissions." 
Could we say instead "CO2 emissions **from energy** comprise..." to make it clear?

Kaya graphs section:
First sentence: "This view shows the drivers of growth in carbon dioxide emissions"
This should say "This view shows the drivers of growth in carbon dioxide emissions **from energy**"

**Comment by travisfranck** [comment]
@yasmeenzahar Can I assign this to the Dec 3rd release?  Assume we can slip this in easily.  Please confirm.

**Comment by yasmeenzahar** [comment]
Yes, confirmed for Dec release
