### ISSUE TITLE
Add instructions on how to push guide updates faster

### ISSUE THREAD

**Issue by chrispcampbell** [climateinteractive/enroads-guide#26]
For every En-ROADS or C-ROADS release, when I push the new release notes there was a delay of a couple hours before the changes would be visible on the docs website.  

Travis and I looked into it and eventually determined that the temporary staleness is probably due to the fact that En-ROADS and C-ROADS guides are "sub projects" of the main-docs project, and RTD may not clear the CDN caches for those right away.

Here's what I found worked the last time this happened:

> I had the usual staleness issue this morning after pushing the En-ROADS release notes.  I triggered a manual build of the `main-docs` project through the admin interface, and after that, I refreshed the page and the latest version of the page showed up.

> So I think that’s our answer; if we want to make the doc changes propagate faster, looks like a manual build on `main-docs` will do the trick.

We should add that to the `rst_setup_guide` document in the repo.

**Comment by travisfranck** [comment]
Updated text in `rst_setup_guide`.
