### ISSUE TITLE
Update guide to reflect changes to Population slider

### ISSUE THREAD

**Issue by chrispcampbell** [climateinteractive/enroads-guide#29]
For reference, see Ellie's updated description here: https://github.com/climateinteractive/en-roads-app/issues/677#issuecomment-729801696

**Comment by chrispcampbell** [comment]
@yasmeenzahar I checked on this issue because I wanted to note that we're changing the population slider to reflect population in 2100 rather than 2050 (see https://github.com/climateinteractive/en-roads-app/issues/868) but it looks like you're already on top of that, so thanks.

I'm reopening this due to one thing I spotted in the guide changes:
https://github.com/climateinteractive/enroads-guide/compare/draft#diff-c9e2342c4c730126426e92b0c555da62d5bbb98e65df5cd1a53cedb13626d942

I think we can now remove or reword this second sentence:

> This input is indexed across the UN's scenarios, where -1 is the low end of the UN’s growth range, 0 is the medium growth scenario, and 1 is the high end of the range.

Since we no longer expose the raw numbers in the range [-1, 1], we probably shouldn't mention those, but @llie probably has a better idea of how to change the wording.

**Comment by chrispcampbell** [comment]
@yasmeenzahar I took a stab at removing the line in 0466384 while I was updating the docs for inclusion in the app (for https://github.com/climateinteractive/en-roads-app/issues/879) because I had to fix a tiny formatting issue, but please feel free to edit or add a sentence back in there to clarify the new slider behavior.

**Comment by yasmeenzahar** [comment]
Thanks Chris, good catch. I added this sentence: "The variable being changed reflects the global population by 2100, in billions of people." If that sounds good, I'll push to draft. 

As a general update to how guide edits edits are going - I've pushed most changes to the draft branch and Phil is giving them a second set of eyes. Once he gives the okay, I'll push to the main/master branch and let you know that they're ready to be pulled into the app. Does that process work for you?

**Comment by llie** [comment]
@yasmeenzahar Was there a reason for removing the "UN Scenario" row of the table? 


lowest growth | low growth | status quo | high growth | highest growth
-- | -- | -- | -- | --
UN Scenario | low end of UN’s 95% range |   | middle of the UN’s 95% range |   | high end of the UN’s 95% range

Seems to me that we should leave it in, since we still refer to the UN Scenarios for the rationale for how we have set the population trajectories. It gives context for why we have the population set the way it is. 

E

**Comment by yasmeenzahar** [comment]
Added back in
