### ISSUE TITLE
Draft URL broken 

### ISSUE THREAD

**Issue by yasmeenzahar** [climateinteractive/enroads-guide#30]
The link to access the draft version of the User Guide is not loading: https://docs.climateinteractive.org/projects/en-roads/en/draft/

The main version of the User Guide is working as expected: https://docs.climateinteractive.org/projects/en-roads/en/latest/

**Comment by chrispcampbell** [comment]
@yasmeenzahar It appears to be loading fine for me.  Are you seeing an error message?  Or is it showing outdated content?

One thing you can try in case it's showing stale content is to force a full reload of the page (Option+Command+R in Safari, Control+Shift+R in Firefox/Chrome).

**Comment by yasmeenzahar** [comment]
Yep seems to be working! I was seeing 'handshake failed' then 'service unavailable' then it just wasn't loading the page and now it's loading very slow but it is showing up eventually so I think it has figured itself out. Will close.
