### ISSUE TITLE
Update the user guide/read the docs for the damage function

### ISSUE THREAD

**Issue by sibeleker** [climateinteractive/enroads-guide#35]
Moved from [en-roads-app issue #1027](https://github.com/climateinteractive/en-roads-app/issues/1027)

We need to update the user guide for the damage function (Feb release).

This is the original: https://docs.climateinteractive.org/projects/en-roads/en/latest/guide/econ_growth.html

I have sent the amendments by email in a minute.

**Comment by yasmeenzahar** [comment]
Looking over these changes now - we tend to just show slider settings for the main slider so these new table formats would differ from the rest of the slider pages. @llie any thoughts on this? Happy to add if it's already been discussed and agreed upon. Sibel's changes attached. 

[Damage_user guide_v1.docx](https://github.com/climateinteractive/enroads-guide/files/5822068/Damage_user.guide_v1.docx)

**Comment by sibeleker** [comment]
Hmm, we needed to give this table for the new sliders, but now we also have them in the slider info text, though not in the table format. I think the table format is easier to explain it to users. If doesn't suit the rest, I am happy to consider different options.

**Comment by sibeleker** [comment]
..and @yasmeenzahar , maybe hold on for this for a few more days, because Chris came up with a new idea for the new sliders. I will review the user guide again to make sure it reflects the final version.

**Comment by sibeleker** [comment]
@philrice-ci I was totally confused about where you asked this question.

OK, here is a revised version of the user guide. Feel free to change if it doesn't fit the convention of user guide.

[Damage_user guide_v2.docx](https://github.com/sibeleker/files/raw/main/Damage_user%20guide_v2.docx)

**Comment by llie** [comment]
Thanks @sibeleker !  I've made a few edits and moved things around some, but it looks good to me. 
My changes tracked in this version (v3): [Damage_user guide_v3.docx](https://github.com/climateinteractive/enroads-guide/files/5851657/Damage_user.guide_v3.docx)

@yasmeenzahar this is going to mark a departure from the level of detail that the User Guide normally covers. We've needed to go this direction for awhile to offer users more details on the advanced sliders, so I think this is the time. 

I added some text about the other economic growth advanced sliders to help make sure that this user guide page ends up balanced, at least in that there are details about all the different advanced sliders. A bigger project that needs to be undertaken at some point is to add more background and details about the advanced sliders throughout En-ROADS. For now we'll approach it piece by piece.

**Comment by yasmeenzahar** [comment]
I've implemented the v3 changes into the draft of the guide here: https://docs.climateinteractive.org/projects/en-roads/en/draft/guide/econ_growth.html

**Comment by yasmeenzahar** [comment]
FYI since these updates have been added to the draft User Guide, they are set up to go live for the Feb release. Since it seems that the damage function release has been pushed to March, should I remove these updates?

**Comment by chrispcampbell** [comment]
@yasmeenzahar Ah, thanks for the reminder; we should keep those edits out of the guide for February.

But to avoid throwing your work away, what we can do is create a branch off of the current `draft` branch, which will preserve your edits for safe keeping.  I just pushed a branch called `yazzy/35-damage-function` for safe keeping.

It looks like you made some other useful edits to econ_growth.rst (like discussion of the separate growth sliders), so could you edit that file (on the `draft` branch) to remove just the damage portions?

**Comment by yasmeenzahar** [comment]
Thanks Chris for this quick thinking. I've just pushed edits to draft that remove the damage portions

**Comment by yasmeenzahar** [comment]
@chrispcampbell should these edits be reincorporated into the user guide for March release?

**Comment by chrispcampbell** [comment]
@yasmeenzahar Oh right, I was wondering what happened to these and forgot we pulled them :smile:  Yes, let's reincorporate.  I'll coordinate with you on Slack.

**Comment by chrispcampbell** [comment]
These changes were reincorporated today for the March release and can be viewed here:
https://docs.climateinteractive.org/projects/en-roads/en/latest/guide/econ_growth.html
