### ISSUE TITLE
Kaya graphs description

### ISSUE THREAD

**Issue by llie** [climateinteractive/enroads-guide#6]
Below is Drew's draft Kaya description with some comments/notes from me in it. Next step @yasmeenzahar take a pass? 

I'm imagining that this will become its own page in ReadTheDocs and then Todd will pull a portion of it into SDE to appear as part of the Kaya graphs description (not added yet).

[Kaya graph description text Aug 2019 v3.docx](https://github.com/climateinteractive/enroads-guide/files/3505804/Kaya.graph.description.text.Aug.2019.v3.docx)

**Comment by yasmeenzahar** [comment]
My edits here: [Kaya.graph.description.text.Aug.2019.v4.docx](https://github.com/climateinteractive/enroads-guide/files/3506938/Kaya.graph.description.text.Aug.2019.v4.docx)

**Comment by yasmeenzahar** [comment]
Ah here it was! Closing for now.
