### ISSUE TITLE
Carbon price and energy consumption dynamic

### ISSUE THREAD

**Issue by llie** [climateinteractive/enroads-guide#7]
From Andrew Greenspan: 

> Drew/Ellie,
> 
> I’ve just started to toy with the beta version, and I want to call attention to cases where the insight in the e-guide (which I think is great) is relatively weak based on how the model is now behaving.  I say now behaving, because the below insight was much more distinct in the prior version.
> 
> See below two screenshots.  I’ve set a high carbon price ($60), and while the blue line is below the black, it’s very slight.  Could be discouraging visually to see that a high carbon price doesn’t have a bigger effect on overall demand – especially if I was prepared to say that it does (in the prior version there is a levelling off).
> 
> If I did this live and felt like the Final Energy Consumption insight didn’t quite land, I would probably show Coal Final Energy Consumption instead where there is a clear and immediate levelling off.
> 
> Another example is renewables subsidy.  Under the prior version, a $.06/kwh subsidy in isolation got us .1 degree.  In beta it’s worth a full half a degree.  That’s a massive difference and one that a facilitator would need to adjust their prepared insights for.
> 
> I just want to point stuff like this out to highlight one of the challenges in facilitating – some of the preparation can become obsolete as the model updates yield different outcomes.  We obviously want the model to use the latest data, I just wonder if there is a way to make sure the e-guide keeps pace or material changes can be noted somehow.

![image](https://user-images.githubusercontent.com/11560745/63105285-80287480-bf4e-11e9-9c0b-28abec6724a5.png)

![image](https://user-images.githubusercontent.com/11560745/63105298-87e81900-bf4e-11e9-9e47-f0418cf4d261.png)

**Comment by llie** [comment]
Seems adding a qualifier like "...with a significant carbon price..." would make it accurate. The effect is just not as a prominent when with the more moderate carbon price Andrew is using (even though it is labelled as "high"). That seem sufficient?

**Comment by yasmeenzahar** [comment]
Qualifier added for carbon price and energy consumption. Will keep issue open since there are a couple other points Andrew made, but feel free to close if you feel it has all been covered.

**Comment by llie** [comment]
Change in draft version looks good. 

Do you see other changes that we should make from his comments? If not, I'd say fine to close.
